# SaneClick Outreach Configuration
# Target: Users frustrated with complex, broken, or expensive Finder context menu tools

competitors:
  # Direct Open Source Competitors
  - "zerodivisi0n/FinderMenu"
  - "RoadToDream/SzContext"
  - "wflixu/RClick"
  - "samiyuru/custom-finder-right-click-menu"
  
  # Popular/Related Tools (Watch for "alternative to X" queries)
  - "fikovnik/ShiftIt" # Window management, but similar audience
  - "rxhanson/Rectangle" # Window management, overlapping user base
  - "linearmouse/linearmouse" # Mouse customization

# Curated listings
launches:
  - platform: "awesome-mac"
    url: "https://github.com/jaywcjlove/awesome-mac/pull/1804"
    date: "2026-02-10"
    status: "merged"
    notes: "99k star repo."
  - platform: "open-source-mac-os-apps"
    date: "2026-02-20"
    status: "merged"
    notes: "47k star repo. PR #1008 merged."
  - platform: "awesome-macOS"
    url: "https://github.com/iCHAIT/awesome-macOS/pull/697"
    date: "2026-02-20"
    status: "submitted"
    notes: "17.8k star repo. PR #697."

search_terms:
  # Problems
  - "finder context menu custom script"
  - "run shell script from finder right click"
  - "automator quick action not showing"
  - "add terminal command to finder menu"
  - "macos right click menu slow"
  - "remove items from finder context menu"
  
  # Alternatives
  - "alternative to Service Station"
  - "alternative to iRightMouse"
  - "better than Automator"
  - "fast scripts finder"
  
  # Feature Requests (that we have)
  - "finder extension script runner"
  - "execute bash script finder selection"
  - "finder context menu submenu"
