name: SaneClick
configs:
  Debug: debug
  Release: release
  Release-AppStore: release

options:
  bundleIdPrefix: com.saneclick
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.8.0

settings:
  DEAD_CODE_STRIPPING: YES
  SWIFT_EMIT_LOC_STRINGS: YES
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
  configs:
    Debug:
      ENABLE_HARDENED_RUNTIME: NO
    Release:
      ENABLE_HARDENED_RUNTIME: YES
    Release-AppStore:
      ENABLE_HARDENED_RUNTIME: YES
  # Warnings
  CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
  CLANG_WARN_BOOL_CONVERSION: YES
  CLANG_WARN_COMMA: YES
  CLANG_WARN_CONSTANT_CONVERSION: YES
  CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
  CLANG_WARN_EMPTY_BODY: YES
  CLANG_WARN_ENUM_CONVERSION: YES
  CLANG_WARN_INFINITE_RECURSION: YES
  CLANG_WARN_INT_CONVERSION: YES
  CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
  CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
  CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
  CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
  CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
  CLANG_WARN_STRICT_PROTOTYPES: YES
  CLANG_WARN_SUSPICIOUS_MOVE: YES
  CLANG_WARN_UNREACHABLE_CODE: YES
  CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
  ENABLE_STRICT_OBJC_MSGSEND: YES
  GCC_NO_COMMON_BLOCKS: YES
  GCC_WARN_64_TO_32_BIT_CONVERSION: YES
  GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
  GCC_WARN_UNDECLARED_SELECTOR: YES
  GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
  GCC_WARN_UNUSED_FUNCTION: YES
  GCC_WARN_UNUSED_VARIABLE: YES

schemes:
  SaneClick:
    build:
      targets:
        SaneClick: all
        SaneClickExtension: all
        SaneClickTests: [test]
    test:
      gatherCoverageData: true
      targets:
        - SaneClickTests
    run:
      config: Debug
    archive:
      config: Release

  SaneClick-AppStore:
    build:
      targets:
        SaneClick: all
        SaneClickExtension: all
    archive:
      config: Release-AppStore

targets:
  SaneClick:
    type: application
    platform: macOS
    bundleId: com.saneclick.SaneClick
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: SaneClick
        excludes:
          - "**/*.md"
      - path: ../../infra/SaneProcess/shared/MoveToApplications.swift
    settings:
      base:
        INFOPLIST_FILE: SaneClick/Info.plist
        PRODUCT_NAME: SaneClick
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.0.3"
        CURRENT_PROJECT_VERSION: "103"
        ENABLE_PREVIEWS: YES
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ARCHS: arm64
        VALID_ARCHS: arm64
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_INJECT_BASE_ENTITLEMENTS: YES
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGN_ENTITLEMENTS: SaneClick/SaneClick.debug.entitlements
        Release:
          DEVELOPMENT_TEAM: M78L6FXD48
          CODE_SIGN_IDENTITY: "Developer ID Application"
          CODE_SIGN_ENTITLEMENTS: SaneClick/SaneClick.entitlements
        Release-AppStore:
          DEVELOPMENT_TEAM: M78L6FXD48
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_ENTITLEMENTS: SaneClick/SaneClick-AppStore.entitlements
          OTHER_SWIFT_FLAGS: "$(inherited) -D APP_STORE"
    postBuildScripts:
      - name: Stub Sparkle for App Store builds
        script: |
          if [ "${CONFIGURATION}" = "Release-AppStore" ]; then
            SPARKLE_FW="${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/Sparkle.framework"
            if [ -d "${SPARKLE_FW}" ]; then
              echo "Replacing Sparkle.framework with empty stub for App Store build"
              # Preserve Info.plist before nuking
              PLIST_TMP="/tmp/sparkle_info_$$.plist"
              cp "${SPARKLE_FW}/Versions/B/Resources/Info.plist" "${PLIST_TMP}" 2>/dev/null || true
              # Nuke entire framework (removes nested Updater.app, XPCServices, etc.)
              rm -rf "${SPARKLE_FW}"
              # Recreate clean minimal framework structure
              mkdir -p "${SPARKLE_FW}/Versions/B/Resources"
              # Create stub dylib that satisfies LC_LOAD_DYLIB
              printf 'void __sparkle_stub(void){}\n' | \
                xcrun clang -x c - -dynamiclib \
                  -install_name "@rpath/Sparkle.framework/Versions/B/Sparkle" \
                  -o "${SPARKLE_FW}/Versions/B/Sparkle" 2>/dev/null
              # Restore preserved Info.plist
              if [ -f "${PLIST_TMP}" ]; then
                mv "${PLIST_TMP}" "${SPARKLE_FW}/Versions/B/Resources/Info.plist"
              fi
              # Create required framework symlinks
              ln -sfn B "${SPARKLE_FW}/Versions/Current"
              ln -sfn Versions/Current/Sparkle "${SPARKLE_FW}/Sparkle"
              ln -sfn Versions/Current/Resources "${SPARKLE_FW}/Resources"
              # Sign: stub binary first, then framework bundle
              /usr/bin/codesign --force --sign "${EXPANDED_CODE_SIGN_IDENTITY}" "${SPARKLE_FW}/Versions/B/Sparkle" 2>&1
              /usr/bin/codesign --force --sign "${EXPANDED_CODE_SIGN_IDENTITY}" "${SPARKLE_FW}" 2>&1
              echo "Sparkle stubbed successfully"
            fi
            rm -rf "${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/Sparkle_XPCServices.framework" 2>/dev/null || true
          fi
        basedOnDependencyAnalysis: false
    dependencies:
      - target: SaneClickExtension
        embed: true
        codeSign: true
        copyPhase:
          destination: plugins
      - package: Sparkle
    info:
      path: SaneClick/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSApplicationCategoryType: "public.app-category.utilities"
        SUFeedURL: "https://saneclick.com/appcast.xml"
        SUEnableSystemProfiling: false
        SUEnableAutomaticChecks: true
        SUPublicEDKey: "7Pl/8cwfb2vm4Dm65AByslkMCScLJ9tbGlwGGx81qYU="

  SaneClickExtension:
    type: app-extension
    platform: macOS
    productType: com.apple.product-type.finder-sync-extension
    bundleId: com.saneclick.SaneClick.FinderSync
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: SaneClickExtension
    settings:
      base:
        INFOPLIST_FILE: SaneClickExtension/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.saneclick.SaneClick.FinderSync
        PRODUCT_NAME: SaneClickExtension
        MARKETING_VERSION: "1.0.3"
        CURRENT_PROJECT_VERSION: "103"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ARCHS: arm64
        VALID_ARCHS: arm64
        CODE_SIGN_STYLE: Manual
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks @executable_path/../../../../Frameworks"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGN_ENTITLEMENTS: SaneClickExtension/SaneClickExtension.debug.entitlements
        Release:
          DEVELOPMENT_TEAM: M78L6FXD48
          CODE_SIGN_IDENTITY: "Developer ID Application"
          CODE_SIGN_ENTITLEMENTS: SaneClickExtension/SaneClickExtension.entitlements
        Release-AppStore:
          DEVELOPMENT_TEAM: M78L6FXD48
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_ENTITLEMENTS: SaneClickExtension/SaneClickExtension.entitlements
          OTHER_SWIFT_FLAGS: "$(inherited) -D APP_STORE"

  SaneClickTests:
    type: bundle.unit-test
    platform: macOS
    bundleId: com.saneclick.SaneClickTests
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Tests
        excludes:
          - "**/*.md"
    settings:
      base:
        DEAD_CODE_STRIPPING: NO
        CODE_SIGN_STYLE: Manual
        ENABLE_HARDENED_RUNTIME: NO
        GENERATE_INFOPLIST_FILE: YES
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
        Release:
          DEVELOPMENT_TEAM: M78L6FXD48
          CODE_SIGN_IDENTITY: "Apple Development"
    dependencies:
      - target: SaneClick
